{% set name = "hello_packaging" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: 0.0.1
  git_url: https://github.com/toonarmycaptain/conda_package.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - hello_packaging

about:
  home: https://github.com/toonarmycaptain/conda_package
