{% set name = "hellopackaging" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
#  git_rev: 0.0.1
#  git_url: https://github.com/toonarmycaptain/conda_package.git
  path: hellopackaging

build:
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

#test:
#  files:
#    - test_greeting.py
#  requires:
#    - pytest
#    - hellopackaging
##  imports:
##    - pytest
##    - hellopackaging
#  commands:
#    - python -m pytest test_greeting.py

about:
  home: https://github.com/toonarmycaptain/conda_package
